apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: visits-service-prod
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: petclinic
    environment: prod
spec:
  project: prod
  source:
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/petclinic-platform.git
    targetRevision: main
    path: helm/petclinic-service
    helm:
      releaseName: visits-service
      valueFiles:
        - ../../helm-values/visits-service.yaml
        - ../../helm-values/prod.yaml
        - ../../helm-values/visits-service-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
